# Generated by Django 5.2.4 on 2025-11-24 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('size_ha', models.FloatField()),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_amount_liters', models.FloatField()),
                ('watering_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yield_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_logs', to='core.yield')),
            ],
        ),
        migrations.CreateModel(
            name='SoilSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('moisture_percent', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yield_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='core.yield')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommended_water_liters', models.FloatField()),
                ('reasoning', models.TextField()),
                ('soil_moisture_estimated', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yield_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.yield')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('amount_kg', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yield_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_logs', to='core.yield')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('evaporation_mm', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='Unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yield_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='core.yield')),
            ],
            options={
                'unique_together': {('yield_field', 'date')},
            },
        ),
    ]
